{- |Contains definition for the Scene object
-}

{-# LANGUAGE TemplateHaskell #-}

module Scene (
    Scene(..), updateScene, drawScene, endScene
) where

import FeyState
import Control.Lens

-- |Contains the functions generated by all scenes
data Scene = Scene {
    _updateScene :: FeyState (Maybe String),
    _drawScene :: FeyState (),
    _endScene :: FeyState ()
}

makeLenses ''Scene