{- |Contains definition for the Scene object
-}

{-# LANGUAGE TemplateHaskell #-}

module Scene (
    Scene(..), update, draw, endScene
) where

import FeyState
import Control.Lens

-- |Contains the functions generated by all scenes
data Scene = Scene {
    _update :: FeyState (Maybe String),
    _draw :: FeyState (),
    _endScene :: FeyState ()
}

makeLenses ''Scene