{- |Contains definition for the Scene object
-}

{-# LANGUAGE TemplateHaskell #-}

module Scene (
    Scene(..), update, draw, endScene
) where

import State
import Control.Lens

-- |Contains the functions generated by all scenes
data Scene = Scene {
    _update :: State -> IO (Maybe String),
    _draw :: State -> IO (),
    _endScene :: State -> IO ()
}

makeLenses ''Scene